language: rust
rust:
  - stable
  - beta
  - nightly
arch:
  - amd64
  - arm64
os:
  - linux
  - osx
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  exclude:
    - os: osx
    - arch: arm64
